language: java
dist: trusty
jdk:
- oraclejdk8
before_script:
- "./gradlew test"
script:
- "./gradlew build"
deploy:
  provider: heroku
  api_key:
    secure: XmNfsVPV6IY5iL0Jhjb2xhwk25S/fEvIb1Jo8MWBslrQBSzZTrovhqEFyauEW3xv1QESGJ2XrPRDm/9WokkLOcu/5kNpdgZwMiMoR7onFraCGJ4iG7zvyS5NegChcJVTYDqUndRfPfsxH7ftwQmZvCzeRroEayjYq7zsHJDhbrVSH5flkkXhlMj1Ik1Vs8+pFSCvP/Cc/3pPNqxV9EmESsFkaLFi24MWgQCROhHMQRqWEmiAC2IyZmHUtQhLnM0TUNeiPvx+Q3ObUtSfCko1lyTRQMzE3db9j5g95PfqIVK+FCs57PiY4yZ467snKs4wSWc+GuSoWqTPuMn0XXg2us6u0Go8+/UbbIC+m1qNVErrd8r6bGSyCK7I72LTOiBW7B3aGiLjliTwVkCblJqHBWb6GvU7AEp0iV4XvD8EYVKqhjKyr0uSUvr8s5YVzK+tHyBrC/u5TbLIbiZ8mWDNQRxdCUN+aov2wZ/WYx4LI/AwJDtrEQ3uC9UR7c013OMFvRyhbejoFOJmkvFQtuvzOgJYggRRexD4OidF+eCZhAPxsNDRfsOtKthFOCvv6llxPQ7AufpHNxD1d08yfBTaa3lVmyDhfn1Aq2XKM7UMzRZrr15zYNJSIHIDURUTWjIGqZXvhs6QXHtlpx3PmMaCMhyebGJSj4Zbf0hsMkHQseo=
  app: minute-man-parking
  on:
    repo: saclave/MinuteManParkingV2
